### PR TITLE
Upgrade config.sub/guess in gsl-1.13.tar.gz to support Linux arm64

### PR DESCRIPTION
**Pull request by Yikun**
Replace config.sub/guess with latest config in trim-gsl-1.13.tar.gz to support Linux aarch64/arm64

```
cd src
# Backup trim-gsl
mv trim-gsl-1.13.tar.gz trim-gsl-1.13-bak.tar.gz

# Extract original gsl
tar -zxvf trim-gsl-1.13-bak.tar.gz

# Replace config.sub/guess with latest config
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.sub -O ./gsl-1.13/config.sub
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.guess -O ./gsl-1.13/config.guess

# Re-tar the tar gz
tar zcvf trim-gsl-1.13.tar.gz gsl-1.13

# Cleanup
rm -rf trim-gsl-1.13-bak.tar.gz gsl-1.13
```

Related: [Bioc-devel] Support for Linux ARM64: https://stat.ethz.ch/pipermail/bioc-devel/2023-January/019398.html
Closes: https://github.com/RGLab/flowClust/issues/24

### CODE REVIEW

**Comment by Yikun** [comment]
```
> BiocManager::install("Yikun/flowClust")

** R
** data
** inst
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘Map’ in package ‘flowClust’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (flowClust)
```

Build passed with this patch

**Comment by Yikun** [comment]
cc @mikejiang @gfinak (who involved in gsl trim https://github.com/RGLab/flowClust/issues/5)

Would you mind taking a look?

**Comment by martin-g** [comment]
Any chance this PR could be reviewed and merged soon ?
flowClust breaks some other packages where it is used as a dependency, e.g. ReorderCluster

**Comment by SamGG** [comment]
For my curiosity, which ReorderCluster package are you talking about?
https://cran.r-project.org/src/contrib/Archive/ReorderCluster/?

**Comment by martin-g** [comment]
@SamGG Thanks for pointing this! Now that I noticed `Archive` in your link the things are more clear to me!
 
My findings started from https://yikun.github.io/bioconductor-0227/report/AneuFinder/kunpeng1-install.html
AneuFinder fails due to missing `ReorderCluster`
Trying to install it locally with `BiocManager::install(c("ReorderCluster"), type = "source", checkBuilt = TRUE)` led me to the problem with `flowClust`.

Now I see that `AnewFinder` also fails on Linux x86_64: https://bioconductor.org/checkResults/3.17/bioc-LATEST/AneuFinder/nebbiolo1-install.html. 
https://r-universe.dev/search/?q=ReorderCluster does not find anything!

So I tried again:
```
BiocManager::install(c("ReorderCluster"), type = "source", checkBuilt = TRUE)
Bioconductor version 3.17 (BiocManager 1.30.20), R Under development (unstable)
  (2023-01-14 r83615)
Installing package(s) 'ReorderCluster'
Old packages: 'flowClust'
Update all/some/none? [a/s/n]: n
Warning message:
package ‘ReorderCluster’ is not available for Bioconductor version '3.17'
```
This time I said `n` to not upgrade `flowClust` and instead of seeing the problem this PR tries to solve I see that `ReorderCluster` is no more available!

Thanks for your help!

**Comment by SamGG** [comment]
Thanks for your feedback. When installing a package, I never update the proposed. from experience, it may make me misleading the messages. I prefer to solve one problem at a time. So I usually update first (or not).
So there are two independent issues and flowClust is not listed as a dependency of ReorderCluster.
For flowClust, I let the real developers answer it. @mikejiang @jacobpwagner 
For ReorderCluster, you have to download the archive version then install the package.
Best.

**Pull request merged**
